print ("BIENVENIDO A PRACJACK")
print ("")
print("Menu")
print ("1.Craps")
print ("2.Spanish 21")
print("3.Casino War")
print("4.Ruleta")
print("5.Mas")
input("Ingrese el numeral del juego que quiere practicar:")
print ("")
print ("CRAPS")
input("Ingrese los numeros de los dados separado por (-) Ejemplo: 2-5 ")
print("No acertaste a los numero, los dados calleron en 6-3")
print("")
print("#Consejo")
print("Recuerda que por el principio de elccion hay mas probabilidad de adivinar si ")
print("das numeros que sumen 7, 8 o 9.")
print("")
input("Deseas continuar jugando?(si o no): ")
input("Ingrese los numeros de los dados separado por (-) Ejemplo: 2-5 ")
print("No acertaste a los numero, los dados calleron en 4-5")
print("")
print("#Consejo")
print("Recuerda que por el metodo de Newton, puedes hacer una regresion lineal para poder")
print("predecir cual va ser la siguienten convinacion de numeros.")
print("")
print("Deseas continuar jugando?(si o no): ")
print("Has tenido varias desaciertos en el juego, recuerda que un buen jugador tambien ")
print("sabe cuando retirarse.")
input()
print("")
print("Te esperamos una proxima vez para que sigas practicando.")